version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run:  composer install
      - run:  phpunit
      - run:  phpcs --standard=PSR2 app/
      - run:  phpmd app/ text codesize,unusedcode,naming
      - run:  phpstan analyse app/ --level 7
      - run:  phptidy app/
